      - name: Update nginx Deployment YAML
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          # image: 뒤에 공백 한 칸 추가
          sed -i "s|image: .*|image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-nginx:$IMAGE_TAG|" ./deployment-nginx.yaml

      - name: Update tomcat Deployment YAML
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          # image: 뒤에 공백 한 칸 추가
          sed -i "s|image: .*|image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-tomcat:$IMAGE_TAG|" ./deployment-tomcat.yaml
